#!/bin/bash

if [ $# -lt 3 ]; then
    echo "Usage: append DIRECTION file1 file2 ... dest"
    echo "i.e.: append -left 01.png 02.png dest.png"
    echo "DIRECTION = [-left|-right|-top|-bottom]"
    exit
fi

DIRECTION=$1
shift;
ARGS=("$@")
DEST=${ARGS[((${#ARGS[@]}-1))]}

FILES="${ARGS[@]:0:((${#ARGS[@]}-1))}"

case "$DIRECTION" in
    "-left"|"-right") OPTIONS='+append';;
    "-top"|"-bottom") OPTIONS='-append';;
esac

case "$DIRECTION" in
    "-left"|"-top") FILES=`echo "$FILES" | awk '{for (i=NF; i>0; i--) printf("%s ",$i);print ""}'`;;
esac

convert $OPTIONS $FILES $DEST
